id: 14b25882726f4d02a265232a601f188b
initial_creation_type: ocr
source_metadata:
  volumes:
    38a343cce41643828afff5b9c51d13ee:
      base_file: v041.txt
      image_group_id: I1PD95886
      title: ''
      total_pages: 1349
      volume_number: 41
