id: D487D22DC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:09:49+00:00'
last_modified: '2022-05-26T14:34:20.276817+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '2196':
      image_group_id: I1PD95886
      title: བདུད་རྩི་འབྱུང་བ་ཞེས་བྱ་བའི་གཏོར་མའི་ཆོ་ག།
      total_pages: 1349
      order: 41
      base_file: 2196.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
